---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/promo/index.md
  label: Promo
- type: document
  path: src/index.md
  label: Main
- type: document
  path: src/conduct/index.md
  label: Code of Conduct
- type: document
  path: src/sponsors/index.md
  label: Sponsors
upload_dir: ".vuepress/public/uploads"
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
